
- name: Add MongoDB GPG key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present

- name: Create MongoDB repository file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/mongodb-org-6.0.list
    content: |
      deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Download and install libssl1.1
  ansible.builtin.shell: |
    wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
    dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

- name: Install MongoDB packages
  ansible.builtin.apt:
    name: mongodb-org
    state: present

- name: Enable and start MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Ensure MongoDB is running
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes

- name: Verify MongoDB is running
  ansible.builtin.command: systemctl status mongod
  register: mongo_status
  failed_when: "mongo_status.rc != 0"

- name: Print MongoDB status
  ansible.builtin.debug:
    var: mongo_status.stdout_lines

- name: Install Python3 and pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Install pymongo
  ansible.builtin.pip:
    name: pymongo
    executable: pip3
    extra_args: --break-system-packages